### ISSUE TITLE
[FEATURE] - Добработать Readme

### ISSUE THREAD

**Issue by ton252** [admiral-team/admiralui-android#102]
**Описание задачи:**
Оформить Readme в таком же стиле, как это сделано на iOS

**Фреймворк**
Нет

**Ресурсы:**
Нет

**Comment by Samuel-Unknown** [comment]
Дублирующаяся задача.

Последние доработки документации сделаны в рамках этого PR:
https://github.com/admiral-team/admiralui-android/pull/103 относящего к задаче https://github.com/admiral-team/admiralui-android/issues/9

Кроме того, перед этим документация разибвалась на части в рамках задачи https://github.com/admiral-team/admiralui-android/issues/11
