### ISSUE TITLE
[BUG] - Некорректная работа Toolbar

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-android#131]
**App version**:  Version 0.0.0 (8) (1649669887)
**OS version**: 11
**Описание**:
В Toolbar нажимаю на минус, а значения все равно прибавляется где выборк картинок

**Шаги воспроизведения:**
1. Toolbar
2. Жму на минус
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге

**Comment by Samuel-Unknown** [comment]
На самом деле баг в InputNumber, а именно в колбеке который неправильно работал отсюда и возникает ошибка в прибавлении/отнимании елементов у тулбара
