### ISSUE TITLE
[FEATURE] - Добавить значок рубля в слайдер как по фигме

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-android#189]
**Описание задачи:**
Добавить значок рубля в слайдер как по фигме

**Фреймворк**
slider

**Ресурсы:**
Ссылка на макеты или ресурсы...

**Comment by muradmur** [comment]
Version 6.0.0
Issue is not actual


![Image](https://github.com/admiral-team/admiralui-android/assets/90680880/1b0f7755-8c50-4fa7-9eff-9c6ffff6f113)
