### ISSUE TITLE
[BUG] - Если слишком длинное наименование темы, то во вкладке Themes наименование отображается некорректно 

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-android#210]
**App version**: 4.1.0
**OS version**: 12
**Описание**: 
> если слишком длинное наименование темы, то во вкладке Themes наименование отображается некорректно 
новые темы или когда переименовываю начинает отображаться только когда перезахожу 

**Шаги воспроизведения:**
1. темы
2. переименовываем на длинное название
3. Шаг 3

**Фактический результат:**
> Название темы отображается некорректно, накладывается на текст

**Ожидаемый результат:**
> Корректное отображение темы
![1тема](https://user-images.githubusercontent.com/101252323/169767545-af19cc23-58ee-41ac-9f91-d9399f13c19d.jpg)
![2тема](https://user-images.githubusercontent.com/101252323/169767547-ed259813-fef5-4138-a660-386dc567121b.jpg)

**Comment by muradmur** [comment]
App version 6.0.0
Os android 13
Issue is not actual
[Demo](https://youtu.be/lzVIzGWtv3c)
