### ISSUE TITLE
[FEATURE] - Присвоить id для кнопок + и - в Badges

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-android#250]
**Описание задачи:**
Присвоить id для кнопок + и - в Badges

**Фреймворк**
XML

**Ресурсы:**
Ссылка на макеты или ресурсы...

**Comment by timbaton** [comment]
необходимо использовать extention fucntion withIndex(matcher: Matcher<View?>, index: Int): Matcher<View?>.

В качестве примера можно использовать BadgesAutoTest:

onView(withIndex(withId(R.id.incrementImageView), 0)).perform(click())
