### ISSUE TITLE
[FEATURE] - Cells - ActinonBar - Secondary - сделать в соответствии с фигмой

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-android#255]
**Описание задачи:**
Cells - ActinonBar - Secondary - сделать в соответствии с фигмой

**Фреймворк**
XML

**Ресурсы:**
Ссылка на макеты или ресурсы...

![image](https://user-images.githubusercontent.com/101252323/172170333-98e935fc-0587-4a66-9ebc-14b039e9ae02.png)

**Comment by Samuel-Unknown** [comment]
Уже реализовано, закрываю
