### ISSUE TITLE
[BUG] - Text fields Standard Masked не переключается иконка

### ISSUE THREAD

**Issue by Samuel-Unknown** [admiral-team/admiralui-android#29]
**App version**: 2.0.0
**OS version**: любая
**Описание**: 
> Text fields Standard Masked не переключается иконка
При установке disabled меняется расстояние между символами в скрытом режиме

**Comment by Samuel-Unknown** [comment]
Этот старый баг уже был поправлен, не смог воспроизвести. 
@Evgeniy-93 убедись что в develop сборках всё ок, например на этой сборке https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-Android-Dev и закрой issue если это так

**Comment by Evgeniy-93** [comment]
все ок
