### ISSUE TITLE
[BUG] - TextField. AdditionalText

### ISSUE THREAD

**Issue by Alesh17** [admiral-team/admiralui-android#321]
**OS version**: 
Android 11. Адмирал 4.5.0

**Описание**: 
При восстановлении стейта не восстанавливается additionalText (но при этом, isError восстанавливается).

**Шаги воспроизведения:**
1. Зайти на экран с textField, засеттить errorText/addtionalText
2. Перейти на другой экран
3. Вернуться на первый экран

**Фактический результат:**
errorText/addtionalText пустые

**Ожидаемый результат:**
errorText/addtionalText должны восстанавливать свое состояние (текст)

**Comment by muradmur** [comment]
Version 6.0.0
API 33
Issue is not actual 
[Demo](https://youtu.be/c1Nt07d7avY)
