### ISSUE TITLE
[BUG] - При переключении на темную тему не видно остальных тем

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-android#434]
**App version**: 5.12.0
**OS version**: 12
**Описание**: 
> Переключаю на темную тему и все наименования тем не видно - dark,light и тд

**Шаги воспроизведения:**
1. Шаг 1
2. Шаг 2
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге

**Comment by muradmur** [comment]
App version 6.0.0
Os android 13
Issue is not actual
[Demo](https://youtube.com/shorts/bD1KGOWGOlY?feature=share)
