### ISSUE TITLE
[BUG] - Allert - поправить кнопку "хорошо"

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-android#439]
**App version**: 5.12.0
**OS version**: 12
**Описание**: 
> Подробное описание проблемы

**Шаги воспроизведения:**
1. Шаг 1
2. Шаг 2
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге
![Screenshot_20230627-171126_Admiral UI Android](https://github.com/admiral-team/admiralui-android/assets/101252323/2a23762f-bbf5-4873-b2bd-b1f7877fb55c)

**Comment by muradmur** [comment]
app version 6.0.0
os android 13
баг не актуален
<img width="376" alt="image" src="https://github.com/admiral-team/admiralui-android/assets/90680880/a37e12df-7a9c-4dc7-a093-4f770ad1b3c6">

**Comment by muradmur** [comment]
Переоткрыл т.к закрыл по ошибке не проверив темную тему
