### ISSUE TITLE
[BUG] - Невозможно отправить сообщение в чате

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-android#440]
**App version**: 5.12.0
**OS version**: 12
**Описание**: 
> Невозможно отправить сообщение в чате

**Шаги воспроизведения:**
1. Шаг 1
2. Шаг 2
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге
![Screenshot_20230627-171258_Admiral UI Android](https://github.com/admiral-team/admiralui-android/assets/101252323/cc65d35f-987e-4b90-80ff-a73cfbf14687)

**Comment by muradmur** [comment]
В рамках задачи
- заменить иконку отправки сообщ на корректную
- прятать fab при открытии клавиатуры
- добавить подсказку в поле ввода
- при состоянии disable разрешить открывать клавиатуру, менять цвет подсказки и делать не активной кнопку отправки

![Image](https://github.com/admiral-team/admiralui-android/assets/90680880/cc2101dc-0eb7-459e-bfab-78c410697402)
![Image](https://github.com/admiral-team/admiralui-android/assets/90680880/c148d197-9dc5-4ecd-b649-2a0da63f71f5)
