### ISSUE TITLE
[BUG] - Linter cells in xml

### ISSUE THREAD

**Issue by timbaton** [admiral-team/admiralui-android#529]
**App version**: 5.18.0
**Описание**: 
Фикс линтера
![telegram-cloud-photo-size-2-5303423440008632044-y](https://github.com/admiral-team/admiralui-android/assets/20974161/9fc297dc-9829-494f-878f-011df644769e)

**Comment by muradmur** [comment]
https://github.com/admiral-team/admiralui-android/pull/591
