### ISSUE TITLE
[FEATURE] - Наименование вкладок и иконки

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-android#74]
**Описание задачи:**
Необходимо поменять наименование вкладок и изображение иконок в соответствии с макетом

**Фреймворк**
UI

**Ресурсы:**
https://www.figma.com/file/SDunEMSNR5pm4ijiDGvWR9/Admiral-Mobile-%E2%80%A8Application-new?node-id=8%3A32

**Comment by muradmur** [comment]
Dublicate #132
