### ISSUE TITLE
[BUG] - Некорректный цвет курсора

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-android#76]
**App version**: 2.0.0(6) (1646172666)
**OS version**: 11
**Описание**: 
Некорректный цвет курсора ввода

**Шаги воспроизведения:**
1. Заходим на главную страницу
2. Нажимаем на поиск
3. Появляется курсор, он салатового цвета

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге

**Comment by muradmur** [comment]
Issue is not actual 
[Demo](https://youtu.be/rUxPvS6oV_8)
