### ISSUE TITLE
[BUG] - Ошибка ввода текста c темной темой Standart

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-android#81]
**App version**: 2.0.0(6) (1646172666)
**OS version**: 11
**Описание**: 
Некорректное отображение текста при переходе на темную тему

**Шаги воспроизведения:**
1. Заходим в Text Fields
2. Заходим в Standart
3. Выбрана темная тема, пишем цифры 1111
4. Переходим на вкладку Error - цифры становятся темными

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге

**Comment by Samuel-Unknown** [comment]
пофикшено в рамках релиза 2.1.0
