### ISSUE TITLE
[FEATURE] - Добавить наименование цвета темы

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-android#99]
**Описание задачи:**
Заходим в темы, выбираем какую-либо тему - в выбранном разделе не отображается наименование выбранной темы

**Фреймворк**
UI

**Ресурсы:**
[Ссылка на макеты или ресурсы...](https://www.figma.com/file/SDunEMSNR5pm4ijiDGvWR9/Admiral-Mobile-%E2%80%A8Application-new?node-id=8%3A32)

UI/UX

**Comment by muradmur** [comment]
Версия 6.0.0
33 АПИ
Задача не актуальна, т.к это обработано в текущей версии приложения
Из того, что можно отметить в данном кейсе - при переходе на экран типографии в лейбле апп бара не отображается название экрана, а еще мне кажется странным, что у темы в названии непонятный отступ снизу. Он есть ток в названии темы

[Демо видео](https://youtu.be/LVNX6IsCT60)

<img width="314" alt="image" src="https://github.com/admiral-team/admiralui-android/assets/90680880/4cae12a1-ebfb-4d06-bc27-d2484fd4c3ad">
